# This workflow will build a MuleSoft project and deploy to CloudHub

name: Test
on:
  push:
    branches: [ main ] 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: cd mule-cicd/target
